name: Ahmad-Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup and Extract
        run: |
          unzip -o Ahmad-Client-Mod.zip
          find . -name "gradlew" -exec chmod +x {} \;

      - name: Build Mod
        run: |
          GW_PATH=$(find . -name "gradlew" | head -n 1)
          cd $(dirname $GW_PATH)
          ./gradlew build

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: Ahmad-Mod-Jar
          path: "**/build/libs/*.jar"
