name: Ahmad Client Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract All Files
        run: |
          unzip -o Ahmad-Client-Mod.zip
          # Agar files kisi folder ke andar chupi hain, toh unhe bahar nikaalo
          find . -maxdepth 2 -name "gradlew" -exec cp -r $(dirname {})/. . \;
          chmod +x gradlew

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Mod
        run: ./gradlew build

      - name: Save Mod File
        uses: actions/upload-artifact@v3
        with:
          name: Ahmad-Client-Mod-Jar
          path: build/libs/*.jar
