name: Ahmad-Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          unzip Ahmad-Client-Mod.zip
          find . -name "gradlew" -exec chmod +x {} \;
      - name: Build
        run: |
          GW_PATH=$(find . -name "gradlew" | head -n 1)
          cd $(dirname $GW_PATH)
          ./gradlew build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Ahmad-Mod
          path: "**/build/libs/*.jar"
