name: Ahmad Client Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Files
        run: unzip Ahmad-Client-Mod.zip

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Mod
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Save Mod File
        uses: actions/upload-artifact@v3
        with:
          name: Ahmad-Client-Mod-Jar
          path: build/libs/*.jar
