name: Ahmad-Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Extract Files
        run: |
          unzip -o Ahmad-Client-Mod.zip
          find . -name "gradlew" -exec chmod +x {} \;
          
      - name: Build Mod
        run: |
          GW_PATH=$(find . -name "gradlew" | head -n 1)
          MOD_DIR=$(dirname $GW_PATH)
          cd $MOD_DIR
          # Hum sirf build folder check karenge
          ./gradlew jar || true
          
      - name: Upload Only Jar
        uses: actions/upload-artifact@v4
        with:
          name: Ahmad-Final-Jar
          path: "**/build/libs/*.jar"
